model_config:
  type: table
  generated_paths:
    test: 1234
    test123: 123

  # Generation config 
  output_dir: '{{ project("generated_paths").sql_output_dir + model("id") + "/bronze" }}' 
  
  
  generation_config:
    - template: "./bronze_table.sql.jinja2"
      
  objects:
    - id: "test"
      test: test1234