# TODO: Now generated by ai, fix this

import pytest
from pathlib import Path

from ramona.model.classes.RamonaProject import Model, Object, RamonaProject
from ramona.model.reference_resolver import TempRefClass
from ramona.model.resolver import ResolveContext, resolve_jinja_yaml


@pytest.fixture
def project_context():
	project = RamonaProject(Path("/tmp/ramona.yaml"))
	project.set_project_config(
		{
			"id": "warehouse",
			"named_paths": {"sql": "./sql/"},
			"enabled": True,
		}
	)

	model = Model(Path("/tmp/models/orders.yaml"))
	model.model_config = {
		"id": "orders",
		"database": "ANALYTICS",
		"retention_days": 30,
	}
	model.register_object(Object(Path("/tmp/models/orders.yaml"), {"id": "customers"}))
	project.register_model(model)

	return project, model


def test_resolves_plain_yaml_and_native_values(project_context):
	project, model = project_context

	result = resolve_jinja_yaml(
		"""
name: customers
enabled: true
columns:
  - id
  - email
""",
		ResolveContext(ramona_project=project, model=model),
	)

	assert result == {
		"name": "customers",
		"enabled": True,
		"columns": ["id", "email"],
	}


def test_resolves_this_project_model_and_scope_values(project_context):
	project, model = project_context

	result = resolve_jinja_yaml(
		("name: customers\n"
		 "project_id: \"{{ project('id') }}\"\n"
		 "model_id: \"{{ model('id') }}\"\n"
		 "sql_path: \"{{ project('named_paths').sql }}\"\n"
		 "retention: {{ model('retention_days') }}\n"
		 "nested:\n"
		 "  inherited_name: \"{{ scope('name') }}\"\n"
		 "  local_name: \"{{ this('configured_name') }}\"\n"
		 "  configured_name: nested_customers\n"
		 "  source_name: nested_customers\n"),
		ResolveContext(ramona_project=project, model=model),
	)

	assert result["project_id"] == "warehouse"
	assert result["model_id"] == "orders"
	assert result["sql_path"] == "./sql/"
	assert result["retention"] == 30
	assert result["nested"] == {
		"inherited_name": "customers",
		"local_name": "nested_customers",
		"configured_name": "nested_customers",
		"source_name": "nested_customers",
	}


def test_resolves_list_expressions_to_native_values(project_context):
	project, model = project_context

	result = resolve_jinja_yaml(
		"paths: {{ project('named_paths').values() | list }}\n",
		ResolveContext(ramona_project=project, model=model),
	)

	assert result == {"paths": ["./sql/"]}


def test_raises_when_this_key_is_missing(project_context):
	project, model = project_context

	with pytest.raises(Exception, match="Problem resolving this missing"):
		resolve_jinja_yaml(
			"name: \"{{ this('missing') }}\"\n",
			ResolveContext(ramona_project=project, model=model),
		)


def test_raises_when_scope_key_is_missing(project_context):
	project, model = project_context

	with pytest.raises(Exception, match="missing not found in scope"):
		resolve_jinja_yaml(
			"nested:\n  value: \"{{ scope('missing') }}\"\n",
			ResolveContext(ramona_project=project, model=model),
		)


def test_ref_defaults_to_current_model(project_context):
	project, model = project_context

	result = resolve_jinja_yaml(
		"customer: {{ ref('customers') }}\n",
		ResolveContext(ramona_project=project, model=model),
	)

	assert result["customer"] == TempRefClass(
		project="warehouse",
		model="orders",
		object="customers",
		original_value="customers",
	)


def test_ref_can_target_another_model(project_context):
	project, model = project_context
	archive_model = Model(Path("/tmp/models/archive.yaml"))
	archive_model.model_config = {"id": "archive"}
	archive_model.register_object(Object(Path("/tmp/models/archive.yaml"), {"id": "events"}))
	project.register_model(archive_model)

	result = resolve_jinja_yaml(
		"event: {{ ref('archive', 'events') }}\n",
		ResolveContext(ramona_project=project, model=model),
	)

	assert result["event"] == TempRefClass(
		project="warehouse",
		model="archive",
		object="events",
		original_value="archive.events",
	)


def test_ref_rejects_more_than_two_arguments(project_context):
	project, model = project_context

	with pytest.raises(Exception, match="used with 1 or 2 arguments"):
		resolve_jinja_yaml(
			"value: {{ ref('one', 'two', 'three') }}\n",
			ResolveContext(ramona_project=project, model=model),
		)
