project_config:
  # Must variables
  models_dir: ./models
  templates_dir: ./templates
  modelchecks_dir: ./modelchecks

  always_clean:
    - project("sql_output_dir")

  # Non protected keywords
  # Some global variables
  project_name: sample_project_1

  # Paths
  sql_output_dir: "./sql/"