model_config:
  id: Copy_model
  description: Model to register actions to copy files

  objects:
    - id: include_folder_copy_action
      template_config:
        - copy_from: 95_python\include
          output_dir: "{{ project('generated_named_paths').orchestration_path }}/include"
