CREATE TABLE TABLE_DEFINITIONS (
    FILE_PATH_DUCKDB_FOLDER VARCHAR NOT NULL,
    ENVIRONMENT VARCHAR NOT NULL,
    DATABASE VARCHAR NOT NULL,
    SCHEMA VARCHAR NOT NULL,
    TABLENAME VARCHAR NOT NULL,
    FILE_LOCATION VARCHAR NOT NULL
);