CREATE TABLE REFERENTIE_GEWAS_VERDAMPING (
    RAW_JSON JSON NOT NULL,

    -- Batch id
    BATCH_ID UUID NOT NULL,
    LOADED_AT TIMESTAMP,
    FILE_ROW_NUMBER INTEGER,

    -- Source info
    SOURCE_SYSTEM VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR
);